# Generated by Django 4.2.21 on 2025-05-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_media_files_postfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostFile',
        ),
    ]
