# Generated by Django 4.2.21 on 2025-05-27 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerresponse',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
